#+TITLE: Youtube Subscriptions Extractor to JSON for NewPipe

* Description
This script extract your youtube subscriptions and parse it into a json. The json-format is adapted to work with the NewPipe application https://github.com/TeamNewPipe/NewPipe

* Installation and Usage
1. Clone the repo

2. ~cd~ into the cloned repo

3. Install and change into python virtual environment
   #+begin_src bash
    source ./install.sh
   #+end_src

   if you want to exit the virtual environment just type:
   #+begin_src bash
    exit
   #+end_src

* Usage
If it does not scroll down to all your subscriber add the ~--scroll~ option and
choose a value bigger than the default option ~100~ like

#+begin_src bash
    python youtube-json-parse.py --scroll 200
#+end_src
** Log into google manually
   1. start the program by
      #+begin_src bash
        python youtube-json-parse.py
      #+end_src
   2. Go to https://medium.com/ , why medium not Google? see [[FAQ]]
   3. Click on Sign In
   4. Sign In with Google
   Even if the message ~"Sorry, we didn’t recognize that account."~ comes,
   you are logged in.
   Quick Check: If you can see your icon next to the url bar, then you are logged in




* How does it work?
It uses selenium, selenium can automate web browsers and this project uses it to get the youtube subscriptions because it is a list, which needs javascript to get loaded ('infinity pages').
* FAQ
** Why do I need to sign in to google over ~medium.com~ ?
Answer: Because google does not allow to log into your account with selenium directly through googles 'sign up' site.

* License

MIT License

Copyright (c) 2020 dmorady1

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
